name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Baixar o código do seu repositório
    - name: Checkout code
      uses: actions/checkout@v4

    # Passo 2: Instalar o Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Passo 3: Instalar o Flutter (A CORREÇÃO ESTÁ AQUI)
    # Isso instala o Flutter automaticamente para o Flet não precisar perguntar
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.24.0' # Versão estável compatível

    # Passo 4: Instalar as bibliotecas do Python (Flet)
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Passo 5: Gerar o APK
    # O comando 'yes |' serve para confirmar automaticamente qualquer outra pergunta que aparecer
    - name: Build APK
      run: |
        yes | flet build apk --verbose

    # Passo 6: Salvar o APK para você baixar
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-producao-apk
        path: build/apk/*.apk
