name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixar código
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Configurar Java 17 (Essencial)
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Configurar Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 4. Instalar bibliotecas
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # 5. Aceitar licenças do Android
    - name: Setup Android SDK Licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

    # 6. Forçar a instalação do Flutter que o Flet quer (O Pulo do Gato)
    # Rodamos um comando simples apenas para ele pedir a instalação e nós aceitarmos com 'yes'
    # O "|| true" garante que o script continue mesmo se o comando reclamar de algo
    - name: Pre-install Flutter Environment
      run: |
        yes | flet doctor || true

    # 7. Compilar o APK (Agora o ambiente já está pronto)
    - name: Build APK
      run: |
        flet build apk --verbose

    # 8. Salvar o arquivo
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-producao-apk
        path: build/apk/*.apk
